---
- name: Show IP address on login screen
  hosts: localhost
  become: yes
  tasks:
  - name: GNOME Desktop - Enable/Disable seconds
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-seconds"
      value: "{{ gnome_topbar_time_seconds | lower }}"
