---
- name: Show IP address on login screen
  hosts: localhost
  become: yes
  tasks:
    - name: GNOME Preferences - Nautilus - Clock Format
      dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
        state: present
