---
- name: Show IP address on login screen
  hosts: localhost
  become: yes
  tasks:
    - name: Add script to /etc/issue
      lineinfile:
        path: /etc/issue
        line: "{{ ansible_default_ipv4.address }}"
        create: yes


