---
- name: Configure auto login on Debian console
  hosts: localhost
  become: yes
  tasks:
    - name: Create directory for getty override
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: '0755'

    - name: Create override.conf for auto login
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin ansible --noclear %I linux

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Restart getty service
      command: systemctl restart getty@tty1
