---
- name: Create SSH key
  hosts: localhost
  tasks:
    - name: Generate SSH key
      ansible.builtin.openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
      register: ssh_key

    - name: Display the public key
      debug:
        msg: "{{ ssh_key.public_key }}"
