---
# Useful for testing with menu and preseeding ..... 

- name: apply a test configuration to the machine
  hosts: localhost
  become: true
  
  roles:
    - setup
    - up2date_debian
    - testmenu
