---
- name: deploywebserver
  hosts: localhost
  remote_user: root
  become: true
 
  tasks:
  - name: install appache
    apt: name=apache2 update_cache=yes state=latest
  
  handlers:
  - name: Reload Apache
    service:
     name: apache2
     state: reloaded
  - name: Restart Apache
    service:
     name: apache2
     state: restarted        
