---

- name: Update MOTD with IP address
  hosts: localhost
  become: yes
  tasks:
    - name: Get IP address
      command: hostname -I
      register: ip_address

    - name: Update MOTD
      copy:
        content: |
          Welcome to your server!
          Your IP address is: {{ ip_address.stdout }}
        dest: /etc/motd
  

