---
- name: Save text to a file
  hosts: localhost
  become: yes

  tasks:
    - name: Write playbook text to a file
      copy:
        content: |
          ---
          #!/bin/bash
          echo "Das ist das script"
        dest: /usr/local/bin/stest
