---
# --- Verzeichnisse für Zielbenutzer ---
- name: Create autostart directory
  ansible.builtin.file:
    path: "{{ autostart_dir }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'

- name: Create Desktop directory
  ansible.builtin.file:
    path: "{{ desktop_dir }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'

# --- Autostart GNOME Terminal ---
- name: Deploy GNOME Terminal autostart desktop file
  ansible.builtin.copy:
    dest: "{{ autostart_dir }}/term.desktop"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
    content: |
      [Desktop Entry]
      Type=Application
      Name=Terminal
      Exec=ptyxis
      OnlyShowIn=GNOME;GNOME-Flashback;
      X-GNOME-Autostart-enabled=true

# --- Desktop Shortcuts ---
- name: Deploy GNOME Terminal desktop file on Desktop
  ansible.builtin.copy:
    dest: "{{ desktop_dir }}/gnome-terminal.desktop"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
    content: |
      [Desktop Entry]
      Version=1.0
      Name=Terminal
      Comment=Open the Terminal
      Exec=ptyxis
      Icon=utilities-terminal
      Terminal=false
      Type=Application
      Categories=System;TerminalEmulator;

- name: Deploy GNOME Disks desktop file on Desktop
  ansible.builtin.copy:
    dest: "{{ desktop_dir }}/gnome-DiskUtility.desktop"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
    content: |
      [Desktop Entry]
      Version=1.0
      Name=GNOME Disks
      Comment=Open GNOME Disks Utility
      Exec=gnome-disks
      Icon=org.gnome.DiskUtility
      Terminal=false
      Type=Application
      Categories=GNOME;GTK;Utility;X-GNOME-Utilities;

# --- GDM Autologin in [daemon]-Section ---
- name: Configure GDM autologin in custom.conf debian daemon.conf
  ansible.builtin.blockinfile:
    path: /etc/gdm3/custom.conf
    marker: "# {mark} ANSIBLE MANAGED AUTOLOGIN"
    block: |
      [daemon]
      AutomaticLoginEnable=True
      AutomaticLogin={{ target_user }}
  notify: restart gdm3

# --- gnome-initial-setup entfernen ---
- name: Ensure gnome-initial-setup is removed
  ansible.builtin.apt:
    name: gnome-initial-setup
    state: absent
