---
- name: Install GDM3
  ansible.builtin.apt:
    name: gdm3
    state: present
    update_cache: true

- name: Install GNOME
  ansible.builtin.apt:
    name: 
      - gnome-panel
      - gnome-applets
      - gnome-terminal
      - gedit
      - firefox-esr
      - gnome-disk-utility
    state: present
    update_cache: true
